version: "3.9"  # optional since v1.27.0
services:
  api:
    container_name: nest-api
    build: .
    ports:
      - "8000:3000"
    volumes:
      - .:/usr/app
  database:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=bank
    ports:
      - "5432:5432"